[server]
headless = true
address = "0.0.0.0"
port = 8000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 200

[browser]
serverAddress = "8859dbcc-e36e-4d16-8217-c288d14b7b73-00-3ce8mxj6fzww0.riker.replit.dev"
serverPort = 8000
gatherUsageStats = false
